name = "Airborn Exploration"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cf8f5aa919c0968588af67eda2bda8183156378a1a21f30fbe31271b8b91e5e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
