name = "Airborn Exploration"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a620511cdd5a0436efa3b4f72ab0e6a44c77970ced24d9edd66d4ad9d10da7bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.11.42"
