name = "Airborn Exploration"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a4dac6b0173abdbe7005b31b1da170748d79d7332de66d55d3c6467aa14e63"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
